server:
  port: 11000

spring:
  application:
    name: msc-zuul-gateway

eureka:
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://local-eureka-server-1:7001/eureka/,http://local-eureka-server-2:7002/eureka/,http://local-eureka-server-3:7003/eureka/

# 服务网关代理
zuul:
  # 踩坑：prefix配置项前必须有'/',否则GG
  # 访问地址：http://127.0.0.1:11000/chennan/myProvider/dept/get?deptNo=1
  prefix: /chennan
  ignored-services: "*"
  routes:
    myProvider.serviceId: msc-provider
    myProvider.path: /myProvider/**


info:
  app:
    name: ${eureka.instance.instance-id}
  company:
    name: www.chennan.com
