server:
  port: 3344

spring:
  application:
    name: msc-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NAMCHERN-GIT/spring-cloud-config.git
          # username: NAMCHERN-GIT
          # password: xxxx
